version: '3.8'
services:
  mongo-container:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass2023
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
